from dataclasses import dataclass
from typing import Any, Optional
from enum import Enum

class PromptModules(Enum):    
    DUMMY_CAMPAIGN_INTENT_GENERATION = "DUMMY_CAMPAIGN_INTENT_GENERATION"
    NON_ECOMMERCE_RECOMMENDED_L0_L1 = "NON_ECOMMERCE_RECOMMENDED_L0_L1"
    NON_ECOMMERCE_SINGLE_PAGE_QUERY = "NON_ECOMMERCE_SINGLE_PAGE_QUERY"
    NON_ECOMMERCE_PAGE_EVALUATOR = "NON_ECOMMERCE_PAGE_EVALUATOR"
    NON_ECOMMERCE_RECOMMENDED_MAPPING = "NON_ECOMMERCE_RECOMMENDED_MAPPING"
    RECOMMENDED_L0_L1 = "RECOMMENDED_L0_L1"
    RECOMMENDED_SECTION = "RECOMMENDED_SECTION"
    TRADE_CLASSIFICATION = "TRADE_CLASSIFICATION"

    BACKGROUND_COLOR_AUTOPOP = "BACKGROUND_COLOR_AUTOPOP"
    TEXT_COLOR_AUTOPOP = "TEXT_COLOR_AUTOPOP"
    BUTTON_COLOR_AUTOPOP = "BUTTON_COLOR_AUTOPOP"
    MISC_COLOR_AUTOPOP = "MISC_COLOR_AUTOPOP"
    
    SEMANTIC_NAME_MAPPING = "SEMANTIC_NAME_MAPPING"
    CONTENT_AGENT = "CONTENT_AGENT"


class Status(Enum):
    SUCCESS = "success"
    ENQUEUE = "enqueue"
    FAILURE = "failure"


@dataclass
class PromptResponse:
    task_name: PromptModules
    status: Status
    result: Optional[Any] = None
    task_id: Optional[str] = None
    error: Optional[str] = None